install:
	cp --force ./provenance.h /usr/include/provenance.h
	cp --force ./provenancefilter.h /usr/include/provenancefilter.h
	cp --force ./provenanceutils.h /usr/include/provenanceutils.h
	cp --force ./provenanceW3CJSON.h /usr/include/provenanceW3CJSON.h
	cp --force ./provenanceSPADEJSON.h /usr/include/provenanceSPADEJSON.h
