install:
	cp --force ./provenance.h /usr/include/provenance.h
	cp --force ./provenancefilter.h /usr/include/provenancefilter.h
	cp --force ./provenanceutils.h /usr/include/provenanceutils.h
	cp --force ./provenancePovJSON.h /usr/include/provenancePovJSON.h
